force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_History__c/Survey_History__c.object-meta.xml
<CustomObject>
    <label>Survey History</label>
    <nameField>
        <label>Survey History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_History__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Histories</relationshipLabel>
    <relationshipName>Survey_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Survey_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_History__c.field-meta.xml
<CustomField>
    <fullName>Survey_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey History</label>
    <referenceTo>Survey_History__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/utilities.cls
public with sharing class utilities {
    @AuraEnabled
    public static List<Object> buildSurvey(List<Survey_History__c> surveyList){
        List<Object> surveys = new List<Object>();
        for (Survey_History__c sh : surveyList) {
            Map<Object, Object> userSurveyMap = new Map<Object, Object>{
                'id' => sh.Id,
                'survey' => sh.Survey__c,
                'surveyName' => sh.Survey_Name__c,
                'name' => sh.Name,
                'createdDate' => sh.CreatedDate,
                'surveyCreatedDate' => sh.Survey__r.CreatedDate,
                'user' => sh.User__r.Name,
                'numberOfQuestions' => sh.Number_of_Questions__c
            };
            Map<String, String> questionsWithAnswers = new Map<String, String>();
            for (Survey_Response__c sr : sh.Survey_Responses__r) {
                String question = sr.Question__c;
                String answer = sr.Answer__c;
                if (!questionsWithAnswers.containsKey(question)) {
                    questionsWithAnswers.put(question, answer);
                } else {
                    String answersString = questionsWithAnswers.get(question) + ', ' + answer;
                    questionsWithAnswers.put(question, answersString);
                }                   
            }
            List<Object> questionsWithAnswersList = new List<Object>(); 
            Set<String> questionsSet = new Set<String>();
            List<String> answersList = new List<String>();
            questionsSet = questionsWithAnswers.keySet();
            answersList = questionsWithAnswers.values();

            for (String q : questionsSet) {
                Map<String, String> formattedQuestionsWithAnswers = new Map<String, String>();
                formattedQuestionsWithAnswers.put('question', q);
                String a = questionsWithAnswers.get(q);
                formattedQuestionsWithAnswers.put('answer', a);
                questionsWithAnswersList.add(formattedQuestionsWithAnswers);
            }
            userSurveyMap.put('questionsWithAnswers', questionsWithAnswersList);
            surveys.add(userSurveyMap);
        }   
        return surveys;
    }
}