force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <label>Answer Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Number__c</fullName>
    <label>Question Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_History__c/Survey_History__c.object-meta.xml
<CustomObject>
    <label>Survey History</label>
    <nameField>
        <label>Survey History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_History__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Histories</relationshipLabel>
    <relationshipName>Survey_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Survey_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey_History__c.field-meta.xml
<CustomField>
    <fullName>Survey_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey History</label>
    <referenceTo>Survey_History__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tst_surveyHistory.cls
@isTest
public class tst_surveyHistory {
    @isTest static void getSurveyHistoryTest() {
        Survey__c s1 = new Survey__c(
        	Name = 'Favorite Food'
        );
        
        insert s1;
        
        Question__c q1 = new Question__c(
        	Name__c = 'What is your favorite Italian food?',
            Question_Number__c = 1,
            Survey__c = s1.Id
        );

        Question__c q2 = new Question__c(
        	Name__c = 'What is your favorite American food?',
            Question_Number__c = 2,
            Survey__c = s1.Id
        );
        
        List<Question__c> questions = new List<Question__c>{
            q1, q2
        };
 
        insert questions;
                
        Answer__c a1 = new Answer__c(
        	Name__c = 'Spaghetti',
            Answer_Number__c = 1,
            Question__c = q1.Id
        );
        
        Answer__c a2 = new Answer__c(
        	Name__c = 'Pizza',
            Answer_Number__c = 2,
            Question__c = q1.Id
        );
        
        Answer__c a3 = new Answer__c(
        	Name__c = 'Linguini',
            Answer_Number__c = 3,
            Question__c = q1.Id
        );
        
        Answer__c a4 = new Answer__c(
        	Name__c = 'Lasagna',
            Answer_Number__c = 4,
            Question__c = q1.Id
        );
        
        Answer__c a5 = new Answer__c(
        	Name__c = 'Hot dog',
            Answer_Number__c = 1,
            Question__c = q2.Id
        );
        
        Answer__c a6 = new Answer__c(
        	Name__c = 'Hamburger',
            Answer_Number__c = 2,
            Question__c = q2.Id
        );
        
        Answer__c a7 = new Answer__c(
        	Name__c = 'Grilled Cheese',
            Answer_Number__c = 3,
            Question__c = q2.Id
        );
        
        Answer__c a8 = new Answer__c(
        	Name__c = 'Sloppy Joe',
            Answer_Number__c = 4,
            Question__c = q2.Id
        );
        
        List<Answer__c> answers = new List<Answer__c>{
            a1, a2, a3, a4, a5, a6, a7, a8
        };

        insert answers;
       
        Survey_History__c history1 = new Survey_History__c(
            Survey_Name__c = s1.Name,
            Survey__c = s1.Id,
            Number_of_Questions__c = 2,
            User__c = userinfo.getUserId()
        );

        Survey_History__c history2 = new Survey_History__c(
            Survey_Name__c = s1.Name,
            Survey__c = s1.Id,
            Number_of_Questions__c = 2,
            User__c = userinfo.getUserId()
        );

        insert history1;
        insert history2;

        Survey_Response__c sr1 = new Survey_Response__c(
            Answer__c = a1.Name__c,
            Question__c = q1.Name__c,
            Survey_History__c = history1.Id,
            Sequence__c = q1.Question_Number__c
        );

         Survey_Response__c sr2 = new Survey_Response__c(
            Answer__c = a2.Name__c,
            Question__c = q2.Name__c,
            Survey_History__c = history1.Id,
            Sequence__c = q2.Question_Number__c
        );

        Survey_Response__c sr3 = new Survey_Response__c(
            Answer__c = a3.Name__c,
            Question__c = q1.Name__c,
            Survey_History__c = history2.Id,
            Sequence__c = q1.Question_Number__c
        );

         Survey_Response__c sr4 = new Survey_Response__c(
            Answer__c = a4.Name__c,
            Question__c = q2.Name__c,
            Survey_History__c = history2.Id,
            Sequence__c = q2.Question_Number__c
        );

        List<Survey_Response__c > responses = new List<Survey_Response__c >{
            sr1, sr2, sr3, sr4
        };

        insert responses;

        String recordId = s1.Id;

        Test.startTest();
        String response = surveyHistory.getSurveyHistory(recordId);
        Test.stopTest();

        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response);
        Boolean isSuccess = (Boolean)responseMap.get('isSuccess');

        System.assertEquals(true, isSuccess);
    }
}