force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <label>Answer Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Number__c</fullName>
    <label>Question Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/tst_surveyForm.cls
@isTest
public class tst_surveyForm {
    @isTest static void getSurveyInfoTest() {
        Survey__c s1 = new Survey__c(
        	Name = 'Favorite Food'
        );
        
        insert s1;
        
        Question__c q1 = new Question__c(
        	Name__c = 'What is your favorite Italian food?',
            Question_Number__c = 1,
            Survey__c = s1.Id
        );

        Question__c q2 = new Question__c(
        	Name__c = 'What is your favorite American food?',
            Question_Number__c = 2,
            Survey__c = s1.Id
        );
        
        List<Question__c> questions = new List<Question__c>{
            q1, q2
        };
 
        insert questions;
                
        Answer__c a1 = new Answer__c(
        	Name__c = 'Spaghetti',
            Answer_Number__c = 1,
            Question__c = q1.Id
        );
        
        Answer__c a2 = new Answer__c(
        	Name__c = 'Pizza',
            Answer_Number__c = 2,
            Question__c = q1.Id
        );
        
        Answer__c a3 = new Answer__c(
        	Name__c = 'Linguini',
            Answer_Number__c = 3,
            Question__c = q1.Id
        );
        
        Answer__c a4 = new Answer__c(
        	Name__c = 'Lasagna',
            Answer_Number__c = 4,
            Question__c = q1.Id
        );
        
        Answer__c a5 = new Answer__c(
        	Name__c = 'Hot dog',
            Answer_Number__c = 1,
            Question__c = q2.Id
        );
        
        Answer__c a6 = new Answer__c(
        	Name__c = 'Hamburger',
            Answer_Number__c = 2,
            Question__c = q2.Id
        );
        
        Answer__c a7 = new Answer__c(
        	Name__c = 'Grilled Cheese',
            Answer_Number__c = 3,
            Question__c = q2.Id
        );
        
        Answer__c a8 = new Answer__c(
        	Name__c = 'Sloppy Joe',
            Answer_Number__c = 4,
            Question__c = q2.Id
        );
        
        List<Answer__c> answers = new List<Answer__c>{
            a1, a2, a3, a4, a5, a6, a7, a8
        };

        insert answers;
       
        String recordId = s1.Id;
        
        Test.startTest();
        String response = surveyForm.getSurveyInfo(recordId);
        Test.stopTest();

        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response);
        Boolean isSuccess = (Boolean)responseMap.get('isSuccess');
        Map<String, Object> results = (Map<String,Object>)responseMap.get('results');
        List<Object> questionsWithAnswers = (List<Object>)results.get('questionsWithAnswers');
        String surveyName = (String)results.get('surveyName');
        System.assertEquals(true, isSuccess);
        System.assertEquals('Favorite Food', surveyName);
    }
    
    @isTest static void saveSurveyResponseTest(){
        Survey__c s1 = new Survey__c(
        	Name = 'Favorite Food'
        );
        
        insert s1;
        
        Map<Object,Object> responseOne = new Map<Object, Object>{
            'question' => 'What is your favorite Italian food?',
            'answer' => 'Pizza',
            'sequence' => 1
        };
        Map<Object,Object> responseTwo = new Map<Object, Object>{
            'question' => 'What is your favorite American food?',
            'answer' => 'Hot dog',
            'sequence' => 2
        };
        List<Object> surveyResponses = new List<Object>{
        	responseOne, responseTwo
        };
        Map<String, Object> params = new Map<String, Object>{
        	'surveyResponses' => surveyResponses,
            'surveyName' => s1.Name,
            'recordId' => s1.Id,
            'numberOfQuestions' => 2
        };
        
		String jsonString = JSON.serialize(params);

		Test.startTest();
        String response = surveyForm.saveSurveyResponse(jsonString);
        Test.stopTest();  
        
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response);
        Boolean isSuccess = (Boolean)responseMap.get('isSuccess');
        System.assertEquals(true, isSuccess);
    }
}